"use client";
import { store } from "@/store/store";
// import "./globals.css";
import "@/css/main.css";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import Header from "@/components/Header/Header";
import Background from "@/components/Background/Background";
// import "@/services/firebase";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body>
          <Background />
          <Header />
          {children}
        </body>
      </Provider>
    </html>
  );
}
